!!com.springrevolution.atuotweet.config.Configuration
appConfig:
  massTrendingChannel: {channelName: Mass Trending, channelURL: 'https://t.me/s/masstrending'}
  massTrendingTag: ''
  showTelegramUI: false
  showTwitterUI: true

telegramChannelList: &id001
- {channelName: ClickAndTweet, channelURL: 'https://t.me/s/mmtweet'}
- {channelName: 2021 Revolution Tweets, channelURL: 'https://t.me/s/RevolutionTweets2021'}

twitterUserList:

- channelList: *id001
  displayName: Kozuki Oden
  lastTweetHistory:
  - {channelURL: 'https://t.me/s/mmtweet', lastTweet: mmtweet/27649}
  - {channelURL: 'https://t.me/s/RevolutionTweets2021', lastTweet: RevolutionTweets2021/58618}
  password: $YourPassword
  tweet: true
  username: $YourUserName
  
- channelList: *id001
  displayName: Kozuki Toki
  lastTweetHistory:
  - {channelURL: 'https://t.me/s/mmtweet', lastTweet: mmtweet/27649}
  - {channelURL: 'https://t.me/s/RevolutionTweets2021', lastTweet: RevolutionTweets2021/58618}
  password: $YourPassword
  tweet: true
  username: $YourUserName
